#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 14 11:01:17 2021

@author: joseph
"""
customers = ["Jay", "Gion", "Dana", "Rob", "Melissa", "AL"]
goods = ["Iphone 13", "Samsung Galaxy 20", "Google Pixel", "Mokia Flip Phone", "Macbook Pro", "Dell Inspiron 15"]
prices = [1299.99, 999.00, 550.79, 345.10, 1450.99, 875.00]
print(len(goods))

'''
#time consuming to go individually
print(goods[0])
print(goods[1])
print(prices[0])
print(prices[1])
'''
#Element by Element Iteration
for good in goods:
    print("Product: " + good)
    
for p in prices:
    print("Prices: ${:.2f}".format(p))

#Loop through indices or number
for x in range(10):
    print(x, end = " ")
    
for y in range(25,45):
    print(y, end = " ")
    
for z in range(920, 1000, 10):
    print(z, end = " ")
    
    print("")
    print("purchases")
    print("-----------------------------------")
    print()
for i in range(6):
    if(customers[i] == "Rob"):
        continue
    print("Client: " + customers[1])
    print("Product: " + goods[i], end = " ----> ")
    print("Prices: ${:.2f}".format(prices[i]))
    
while(True):
    purchase = input("Do you have another purchase? ")
    if(purchase == "yes" or purchase == "Yes"):
        c = input("Customer name: ")
        p = input("Product: ")
        cost = float(input("Cost: "))
        customers.append(c)
        goods.append(p)
        prices.append(cost)
    else:
        break
